### PR TITLE
Endpage content

### PR DESCRIPTION
**Pull request by nicolasfranck**
See https://github.com/LibreCat/LibreCat/issues/791

### CODE REVIEW

**Comment by vpeil** [comment]
ok, but then we need some startup script for the Mojo app, e.g. `bin/mojo-app.pl`

Plus some documentation how to set this up with an apache proxy.

**Comment by nicolasfranck** [comment]
@vpeil there is no need to create an extra startup script (as boot.sh), as this is the way to start a plack application:

```
plackup bin/mojo-app.psgi -p 5000
```

**Comment by vpeil** [comment]
ah, great. Haven't noticed the one, sorry.

**Comment by vpeil** [comment]
@nicolasfranck I think, we need to revert 95a0d42 to make that PR consistent.

**Comment by nics** [comment]
the mojo app should just be removed from the cascade mounted under '/api' in bin/app.pl, that also solves the problems, no need to have a separate startup script for mojo.

```
    mount '/api' => $mojo_app;
    mount '/' => $dancer_app;

```
these lines should also be removed from LibreCat::Application:
```
    push @{$self->renderer->paths}, @{librecat->template_paths};

    $r->any(
        '/*whatever' => {whatever => ''} => sub {
            my $c        = shift;
            my $whatever = $c->param('whatever');
            $c->render(template => '404', handler => 'tt2', status => 404);
        }
    );
```
sharing templates between mojo and dancer is problematic (as witnessed by the warnings when running the tests)

**Comment by nicolasfranck** [comment]
@vpeil @nics ok will fix this in branch fix_api_filestore, as it is related

**Comment by vpeil** [comment]
@nicolasfranck @nics I have pushed changes as suggested above.

**Comment by nicolasfranck** [comment]
@vpeil wait,  I've prepared a working bin/app.pl in another which I'll merge once I fixed some more internal work. I'll end this pull request for now. Sorry.

**Pull request closed without merging**
