### PR TITLE
Sass refactor

### PR DESCRIPTION
**Pull request by verheyenkoen**

### CODE REVIEW

**Comment by verheyenkoen** [comment]
@phochste You mean these icons: 
image

**Comment by phochste** [comment]
@verheyenkoen Yes In the image above they have a correct spacing. In the sass and fontawesome branch they are glued to the text 'Home' 'My Publication List' ...

**Comment by verheyenkoen** [comment]
@phochste This is what I get on the sass_refactor branch.

**Comment by vpeil** [comment]
then that's a problem of the font_awesome branch, only.

**Comment by phochste** [comment]
Nope. switch back between 'dev' and 'sass_refactor' gives other layouts. With cleaning the browser cache:

Switching to sass_refactor:
screenshot_04_10_2017 _14_23

Switching back to dev:
screenshot_04_10_2017 _14_24

**Pull request merged**
