### PR TITLE
Remove citation feature

### PR DESCRIPTION
**Pull request by vpeil**
# What is does:

- Removes the citation feature from this repository as proposed by #830 
- Functionality is contained in a separate layer: https://github.com/LibreCat/librecat-citation
- Activating this layer should lead to the same result as before. 

# How it works:

- With the librecat-citation layer active a hook triggers the generation of citation string at `publication-update`. These citations are stored in a separate bag and get merged into the index record only.

### CODE REVIEW

**Comment by vpeil** [comment]
I removed the custom RTF exporter because I found a better solution via pandoc: this is contained in https://github.com/LibreCat/librecat-citation

One can export publication lists in `docx` and `odt` formats now.

**Comment by phochste** [comment]
@vpeil what is the status on this aparently there are still references to the citation engine in the code. E.g. `publicaton/record.tt` as was found out by @nicolasfranck . I don't know if there are more bits and pieces?

**Comment by nicolasfranck** [comment]
@phochste I and Vitali have agreed to split those templates into smaller pieces, and to include those pieces, controlled by configuration. Of course, it is kind of ridiculous to add a configuration option to include a template in `views/topbar.tt`.

**Comment by vpeil** [comment]
There are a lot more places where citations are mentioned. So it would be easier for the moment to leave it as is.

**Pull request closed without merging**
