### PR TITLE
add sorting to admin's project list

### LINKED ISSUE #544: Project list: No sorting
The project list under /librecat/admin/project has no sorting.

### PR DESCRIPTION
**Pull request by vpeil**
fixes #544

### CODE REVIEW

**Comment by vpeil** [comment]
do not merge, please. There's still a test failing

**Comment by vpeil** [comment]
does not work, I just close this PR

**Comment by nicolasfranck** [comment]
@vpeil what did not work exactly?

**Comment by vpeil** [comment]
too long ago, I don't remember. I you like, check this out and have a look.

**Pull request closed without merging**
