### PR TITLE
Delegate and Datamanager conflict

### PR DESCRIPTION
**Pull request by petrakohorst**
As mentioned in ticket #711 the sub ```by_user_role``` in ```/LibreCat/Access.pm``` does not consider the currently chosen user role, but only checks if the user account contains ANY role that has rights to edit this publication.

So as a reviewer for example a user would also be able to edit (e.g. from the frontdoor, where the edit link is displayed according to the result of can_edit) a publication which they only have delegate rights to.

This is not a security issue, but more of a "let's not mix up the roles" issue.

Solution:   
In ```/LibreCat/Permission.pm``` in the sub ```_can_do_action``` (which is the central sub for all the can_do_ subs), pass the current user role to the access sub ```by_user_role```.

And in ```/LibreCat/Access.pm``` in the sub ```by_user_role``` (in addition to some minor renamings) add the simple check "next unless current role eq permitted role".   
So in this sub we only accept roles that are 1. permitted for this publication, 2. roles/rights the user actually has and now 3. only the role the user has currently chosen.

### CODE REVIEW

**Comment by nicolasfranck** [comment]
@petrakohorst what do you mean by "choose their role"? When they change their role by clicking on one of the options in the upper right corner (settings -> change role)?

What is actually the reason behind this behaviour? Why do we want to change a role?

I've seen problems with session.role going out of sync, especially after updating it
in the database (test it out and you'll see)..

**Comment by petrakohorst** [comment]
@nicolasfranck Yes, I meant "change their role"... not "choose their role" (which they are not allowed to do themselves for security reasons, of course).

**"Why do we want to change a role?"**   
In our local system in Bielefeld there are several use cases for changing a role.

1. ```super_admins``` often change their roles to ```user```, ```delegate``` or ```reviewer``` to be able to reproduce errors the user has found. We even go as far as giving ourselves the exact roles and permissions a reviewer or delegate has (exact departments the reviewer has rights to) so we are able to see exactly what the reviewer is seeing.
2. A ```reviewer``` or ```delegate``` sometimes needs to change their role to ```user``` in order to find "lost" publications. They will sometimes enter a publication for a professor or for a subdepartment but forget to link the person or enter the corresponding department in the form. Then they save the publication and view the list again as reviewer/delegate, the publication is gone.   
The solution for them is to change their role to ```user``` (which displays all publications they are ```creator``` for), edit and correct the publication and then they can switch back and continue editing the delegate list or the reviewer list.
3. Some users may have both a ```reviewer``` role for a (sub)department AND ```delegate``` rights for one or more professors. Depending on what they want to work on, they need to change their role to switch between their "workspaces" so to speak.

------

I have made the changes proposed in this PR in our local LibreCat installation (in the core) in September 2020 and it has been running like this ever since without any problems. I have not noticed ```session.role``` going out of sync in our system so far.

**Comment by nicolasfranck** [comment]
@petrakohorst so in fact you want to able to act as another user? 

I was thinking about that some time ago, but there is one problem:
LibreCat does not enforce the [whitelist](https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App.pm#L176) (during authentication) to be
the same as the internal bag `users` (`find_by_username` uses config `user.sources` which can have different stores),
so you cannot just use the `users` to present a selectbox.

see also: https://github.com/LibreCat/LibreCat/issues/908, https://github.com/LibreCat/LibreCat/issues/748

**Comment by petrakohorst** [comment]
> so in fact you want to able to act as another user?

Yes, that is basically the functionality of the role ```delegate```. But it is a "act with the same rights as" rather than a "act AS" another user. Account and login boundaries will not be crossed.

The same goes for ```reviewers```. They act with a different set of edit rights than their basic user role permits. But they do not act as another user.

How does this PR connect to the `find_by_usernames` function and the whitelist/user authentication problems? And what do you mean by "use the `users` to present a selectbox" - what kind of selectbox do you refer to?

**Comment by nicolasfranck** [comment]
@petrakohorst if I want to create a "login as" functionality (for super admins), I need a source database and present the users in a select box (or something similar).

**Comment by vpeil** [comment]
> @petrakohorst so in fact you want to able to act as another user?
> 
> I was thinking about that some time ago, but there is one problem:
> LibreCat does not enforce the [whitelist](https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App.pm#L176) (during authentication) to be
> the same as the internal bag `users` (`find_by_username` uses config `user.sources` which can have different stores),
> so you cannot just use the `users` to present a selectbox.
> 
> see also: #908, #748

No, this is not about "impersonation". It is about the following use case: 1 user has different roles, and depending in what role one is currently logged you can do or see stuff or not. While logged in, the user can change his or her role.

**Comment by petrakohorst** [comment]
@nicolasfranck I think there was a misunderstanding. This PR is not about creating a new functionality. The system already does everything we need it to do as is. There is no need for a "login-as" functionality.   
We have users (secretaries) needing to edit publications of their professors. For this we grant them edit rights to those exact publications (delegate role) - that is the main use case.

Now, if this secretary also has the job of editing all research_data publications of her department (data_manager role), then being able to choose between those two roles will cause an error: The secretary/delegate is only able to edit publications of their professor - that are ALSO research_data publications with a certain department attached to it.   
It's a pretty wild mixup of the rights of the two roles. See also Ticket #711

That's what I have fixed in this PR.

**Comment by nicolasfranck** [comment]
@nics @phochste I am not really familiar with this kind of authorization. Can you comment on this?

**Comment by phochste** [comment]
@nicolasfranck Hi , I am also not familiar with the delegate / datamanager workflow. But the best strategy for you would be in this case:

- Check with @vpeil and @petrakohorst if they agree on the intentions of the workflow
- Check if you can run the code
- Check with @petrakohorst if you can simulate a test and check that this test works
- If you can confirm the test is working and code is in good shape and @vpeil and @petrakohorst agree that what the delegate/datamanager workflow intends to do is correct, then you can merge. If further issues might popup, they will be new tickets.

**Comment by nicolasfranck** [comment]
@petrakohorst @vpeil as I understand, this PR wants two things:

* fix situation where either role data_manager or delegate is evaluated, and when one of those two fail, it completely fails
* restrict access to the role that is chosen in the UI

I confer with the first option, but not directly with the second. Why do we even want to have an option that says "restrict myself to this role today"? I know it is already in the code, but shouldn't things like that be transparent? It is not uncommon that users have multiple roles, and that the underlying rights overlap

**Comment by nicolasfranck** [comment]
@petrakohorst right I see your comment above about why you want to change roles..

**Review by nicolasfranck — APPROVED** [review]

**Pull request merged**
