### PR TITLE
support schema draft 07

### PR DESCRIPTION
**Pull request by nicolasfranck**
json schema draft 07 supports if-then-else (sub schema).
This way we can add some conditional validation into the
model. I'm not sure, but is there some conditional validation
in the frontend now, and that we can/should get rid of?

### CODE REVIEW

**Comment by nicolasfranck** [comment]
Sigh, the tests are failing because of an unrelated test: t/Catmandu/Plugin/DynamicChecksum.t
Anyone an idea what happened here?

**Comment by nicolasfranck** [comment]
So wait for https://github.com/LibreCat/LibreCat/pull/850

**Comment by nicolasfranck** [comment]
but I'm a bit confused about why in continuous-integration/travis-ci/pr that plugin test does succeed.

**Comment by vpeil** [comment]
@petrakohorst @nicolasfranck I think there are conditional validation checks in the frontend handled by a javascript.

**Pull request merged**
