### PR TITLE
remove bielefeld background reference, images have been deleted earlier

### PR DESCRIPTION
**Pull request by vpeil**
what is left: need to re-generate main.css, (I am getting some npm errors on my installation)

### CODE REVIEW

**Comment by vpeil** [comment]
@verheyenkoen The images files were in the repo (we removed it at some point). So my thought was also to cleanup up these references. Either we rename them, if you'd like to keep a background image or we remove this completely. 

As decribed, of course the main.css needs to be regenarted, but I wasn't able to do this.

**Comment by verheyenkoen** [comment]
@vpeil I regenerated the css file for you.

**Comment by vpeil** [comment]
thanks

**Comment by phochste** [comment]
Thanks!

**Pull request merged**
