### PR TITLE
Fix permissions bug in edit links (search result list) for reviewers.

### PR DESCRIPTION
**Pull request by petrakohorst**
**Problem:**   
As a reviewer for department `xyz` my list of "allowed" publications is displayed correctly. But some of the entries (if not all of them) are not editable. This happens when the entry does not have `xyz` itself as department, but some subdepartment of it.   
The reviewer role depends on the department tree to check if a publication belongs to department `xyz` and thus the reviewer has edit rights to it.

`_can_do_action` checks against publications from the main store, but this PR https://github.com/LibreCat/LibreCat/pull/804 moved the department tree from the main store to the index.

Quick fix:   
When checking for permissions in `_can_do_action`, don't check in main store, but in index. (Additionally: set "live" parameter in template.)

### CODE REVIEW

**Comment by nicolasfranck** [comment]
@petrakohorst what is the reason for setting the parameter to `live`?
The cache is expected to have short living objects, but if you refetch
every record from the index, after you fetched the same list, it is going
to be slow again..

Maybe I should remove the configuration option `expires_in` from
the configuration because this is internal stuff, and only a stupid "fix"
for not using the fetched list of publications in the first place.

**Comment by petrakohorst** [comment]
The "live" parameter is used to avoid calling `get_cached_publication`, which retrieves the rec from the main store. 

Alternatively we might change `get_cached_publication` to retrieve the record from the index instead of the main store. Then we may be able to stick to calling cached publications here.

**Comment by nicolasfranck** [comment]
> The "live" parameter is used to avoid calling `get_cached_publication`, which retrieves the rec from the main store.
> 
> Alternatively we might change `get_cached_publication` to retrieve the record from the index instead of the main store. Then we may be able to stick to calling cached publications here.

Well you just replaced `h->main_publication` by `h->publication` which is the search bag, so that would solve your problem, not?

The "live" parameter (added by @phochste ) is just some internal thing to avoid hitting the cache, and is primarily used when downloading a file.
Apart from that, I haven't seen a good reason for it, as the cache lifetime is actually low.

**Comment by petrakohorst** [comment]
`my $pub = $opts->{live} ? h->publication->get($id) : get_cached_publication($id);` only uses the freshly changed `h->publication` if the parameter `live` is set.

Without `live = 1` it uses `get_cached_publication`, which fetches the record from the main store again.

**Comment by nicolasfranck** [comment]
@petrakohorst the cache only lives for 5 seconds; it is only meant to speed up permission checking during the same request. I actually intend to add a dancer hook `after` that clears the cache on the end of the request (like Rails does for example).

**Comment by petrakohorst** [comment]
So should I just change this line https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Controller/Permission.pm#L29 to `$pub //= h->publication->get($id);`?   
And then remove the live=1 changes from the template?

**Comment by nicolasfranck** [comment]
@petrakohorst I prepared a [PR](https://github.com/LibreCat/LibreCat/pull/950) that would make the option `live` obsolete.

**Comment by petrakohorst** [comment]
Perfect! With your latest changes to this PR everything works as it should!

**Pull request merged**
