### PR TITLE
Elasticsearch 6.5 support

### PR DESCRIPTION
**Pull request by nics**
This PR adds support Elasticsearch 6.5 and addresses issue #579. This is a breaking change that requires reindexing and updating your config because:
- ES types are deprecated, so LibreCat types (and their bags) are now mapped to their own index
- the ES mapping and query dsl has changed

### CODE REVIEW

**Comment by vpeil** [comment]
@nics can we make the host configurable? Some people might want to run ES on a different host.

**Comment by nics** [comment]
isn't it already throught the store config?

**Comment by vpeil** [comment]
yeah, seems to be so. I remember one use case in the previous version, where the indexing commands where host agnostic, but maybe I mixing things up. just ignore my comments

**Comment by phochste** [comment]
Can this pull request be resubmitted from the dev branch and not the master branch? This will make it easier for me to review and follow up.

**Comment by nics** [comment]
replaced by pull request #716 against dev branch

**Pull request closed without merging**
