### PR TITLE
Schema org json ld

### PR DESCRIPTION
**Pull request by vpeil**
This PR introduces schema.org in JSON-LD. This is a more flexible and extensible approach than the speical attributes within the html.

The mapping can be improved/extended in the future.

And it solves #598.

### CODE REVIEW

**Comment by phochste** [comment]
@vpeil Can you give some hints how I can see in the web interface the effects of this pull request?

**Comment by vpeil** [comment]
@phochste look at the html source on the frontdoor. At the end of the page you should see

```js
<script type="application/ld+json">
...
</script>
```

with some json inside.

**Comment by nicolasfranck** [comment]
@vpeil @phochste I think it needs to be documented what this change means for ones local branch of librecat. If someones has overridden a view (e.g. views/publication/record.tt), he/she would loose this functionality. 

Thanks for this change!

**Comment by nicolasfranck** [comment]
@vpeil : I think the json object needs to be a regular object, not an array of objects. The use of "export_to_string" is probably the cause for this

**Comment by vpeil** [comment]
yes, are there still references left?

**Comment by nicolasfranck** [comment]
ah sorry, I was looking in my own junkyard

**Comment by nicolasfranck** [comment]
Look for "itemscope" and "itemtype" in the views:

* views/publication/record.tt
* views/project/record.tt
* views/header.tt
* views/home.tt

**Comment by vpeil** [comment]
ok, will do.

**Comment by vpeil** [comment]
> I think the json object needs to be a regular object, not an array of objects. The use of "export_to_string" is probably the cause for this.

I don't understand the problem.

**Pull request merged**
