### PR TITLE
cleanup mojo application and mount differently

### PR DESCRIPTION
**Pull request by nicolasfranck**
* mount dancer and mojo under different path with different rules:
  * dancer: session based
  * mojo: open or token based
* remove references to api_access from config and LibreCat::App. Note that certains paths in the api must be protected by the frontend server now (which is more efficïent), while this was done by librecat. 
* default route in mojo should return json, not using a template system.

This should also fix https://github.com/LibreCat/LibreCat/issues/791

### CODE REVIEW

**Comment by nicolasfranck** [comment]
note done yet, sorry

**Comment by phochste** [comment]
@nics I can't accept a pull request that will not have an IP check on the API. Can there be a solution where the API is started on a different port?

**Comment by nics** [comment]
comment is meant for @nicolasfranck?
why can't you have an ip check on a path?

**Comment by nicolasfranck** [comment]
Ok, I will remove mojo app from bin/app.pl

**Comment by vpeil** [comment]
I don't understand the problem. Isn't it enough to protect the api with the authorization header?

**Comment by vpeil** [comment]
Mount mojo application in bin/app.pl, please.

**Pull request merged**
