### PR TITLE
Pr/issue 718

### PR DESCRIPTION
**Pull request by vpeil**
Solves #718.

+ extends OAI config with all publication typs as sets (and better grouping)

### CODE REVIEW

**Comment by phochste** [comment]
@vpeil I suspect the software part of this pull request for OpenAIRE v4 support will be working. But we feel some concerns here in Ghent on the interpretation of the mapping. E.g. to suddenly map 'review' records as 'book review' and 'conference_abstract' as 'conference poster' and putting all these things in a COAR tree is open for a whole lot of interpretation of the data. Do you see that there could be a bit of "uncomfort" to reinterpret the data this way? 

Here in Ghent we use our own OAI port to provide data, so we have are own choice if we want to follow OpenAIRE v4 or not. Just to check with the group in want way we can best add this to the code base. Is this mapping doable as first start?

**Comment by vpeil** [comment]
@phochste we should discuss this with @joschirr this week.

**Comment by vpeil** [comment]
use more broader type mapping instead of lying ;-)

**Comment by vpeil** [comment]
I have pushed an update with a more general type mapping.

**Pull request merged**
