### PR TITLE
see #233, prepare user search: makes retrieval much faster

### PR DESCRIPTION
**Pull request by vpeil**
this solves #233 (but not like described in the issue).

Please provide some feedback.

### CODE REVIEW

**Comment by vpeil** [comment]
Do we want to display publication counts? In that case I have to modify this PR a bit.

**Comment by phochste** [comment]
Yes, the publication count is shown in the departments tab. It would preferably also be present in the authors and projects tab.

**Comment by vpeil** [comment]
@phochste requested changes implemented.

**Comment by phochste** [comment]
Ok thanks
@verheyenkoen Can you update the cypress tests? In new `dev` branch the test will fail to dynamically load the user count on the Manage User Accounts page and User tab on the Front page

**Comment by verheyenkoen** [comment]
@phochste Removed the specific test. Was testing for the AJAX to work which is now removed so no use in keeping a test for that.

**Pull request merged**
