### PR TITLE
Feature/seamless index switch

### PR DESCRIPTION
**Pull request by vpeil**

### CODE REVIEW

**Comment by vpeil** [comment]
@phochste I think the idea was the following:
start with a fresh elasticsearch (`curl -XDELETE localhost:9200/*`)
then run `bin/librecat index initialize`.

**Comment by phochste** [comment]
@vpeil The problem is when you execute `bin/librecat index initialize` a second time, the command crashes and both indexes are deleted. At least the command should work (re initialize something) or prevent you from initializing an index that is already ok.

**Comment by vpeil** [comment]
@phochste please, have a look at the latest commit f7797a2

**Comment by phochste** [comment]
This branch is too big to merge. I've created a new branch only containing the index switch code

**Pull request closed without merging**
