### PR TITLE
Add the oa sign to records in the publication list view.

### PR DESCRIPTION
**Pull request by petrakohorst**
Only if one of the files is oa, of course.

Sign is displayed next to year, type etc.

### CODE REVIEW

**Comment by nicolasfranck** [comment]
"oa" is the same as access_level=open_access I guess? Better to make this explicit. "oa" is probably meant as a derived field for facets only?

**Comment by vpeil** [comment]
yes, `oa` is a derived field (created at index time). But it also respects OA-URLs, so it is better to use this field instead of mutliple or statements.... I think this can be merged safely.

**Comment by nicolasfranck** [comment]
@vpeil it becomes a problem when someone decides that this derived field should not be created, because he/she does not want this facet..

**Comment by petrakohorst** [comment]
If someone decided not to create the oa field at index time, the oa sign would simply never be displayed in the list. It would not break any code. And if they want the oa sign, they would simply have to create the oa flag during indexing.

**Pull request merged**
