### PR TITLE
Pr/custom mount path

### PR DESCRIPTION
**Pull request by vpeil**

### CODE REVIEW

**Comment by nicolasfranck** [comment]
Wouldn't it be better to do this in the proxy server? I.e. set the prefix there?

**Comment by nicolasfranck** [comment]
With only "/whatever", some paths will not be caught by Dancer, but by Plack itself. So your "page not found" would be different

**Comment by vpeil** [comment]
I had this as a feature request from an institution using a load balancer. Of course, one needs to set the `uri_base` accordingly. One can do load balancer -> apache reverse proxy -> librecat web service, but the extra layer with apache reverse proxy seems to be superfluous.

**Comment by nicolasfranck** [comment]
You can also make port 5001 available for the load balancer only (using firewall settings), and set "uri_base" (that's what it is made for) in the config to match the prefix from the load balancer. If understand correctly, you're starting plack on port 80?

**Comment by vpeil** [comment]
aha, looks like a better solution. We will try this.

**Comment by vpeil** [comment]
Please, wait with this PR.

**Comment by nicolasfranck** [comment]
@vpeil : what have you decided?

**Pull request closed without merging**
