### PR TITLE
Pr/doi register

### PR DESCRIPTION
**Pull request by vpeil**
Solve #284 partially (DOI regsitration)

### CODE REVIEW

**Comment by vpeil** [comment]
@phochste changes made as requested

**Comment by vpeil** [comment]
@phochste this on is ready to merge (and the longer it is here, the more work I have, to keep that one in sync with dev branch).

**Comment by phochste** [comment]
I need some feedback from @vpeil or @nics It was for me quite hard to test and debug this code.

In https://github.com/LibreCat/LibreCat/blob/pr/doi_register/lib/LibreCat/Hook/register_doi.pm#L23 a `librecat->log->debug` is used which results in no logging output when setting the log4perl parameters. I don't know why this is.

For @vpeil :

-  I assume one needs to add a `register_doi` hook added in `hooks.yml` `hooks.publication-publish.after_fixes` to make this work? (Or what is the best place?)
-  Also the `forms.yml` needs to be edited to activate the registration for `doi` fields
- The `LibreCat::Hook::register_doi` requires a seperate `hook.register_doi` configuration which is not defined and the supplied example doesn't work with the standard DOI prefix defined in `catmandu.local.yml-example`

..This `hook.register_doi` is actually what seems to be the `catmandu.local.yml-example` `doi` configuration. Can't this YAML section not be (re)used?

**Comment by vpeil** [comment]
About the logging: no idea why this happens.

In #284 I have mentioned the wiki: https://github.com/LibreCat/LibreCat/wiki/DOI-Registration. Thjis article should contain everything one needs. Should it also be documented somewhere in the code?

I will have a look at the example configuration.

**Comment by vpeil** [comment]
@phochste this commit provides the suggested config modification
https://github.com/LibreCat/LibreCat/pull/493/commits/c7da26b3b7b889ef90645a0ea5ff65b3ef7a71ea

**Comment by phochste** [comment]
@vpeil About the logging: @nics  helped me:

This code only works when the top level `LibreCat` is set to `DEBUG` mode:

```
librecat->log->debug("...");  
```

This code will work when the `LibreCat::Pkg::Whatever` is set to `DEBUG` mode:

```
with LiberCat::Logger

sub  ... {
   
   $self->log->debug("...")
}
```

**Pull request closed without merging**
