### PR TITLE
remove legacy routes for next major version; if necessary for some in…

### PR DESCRIPTION
**Pull request by vpeil**
…stallations this can be handled by a webserver

### CODE REVIEW

**Comment by phochste** [comment]
@vpeil can you provide a working example how a webserver could route the old urls?

**Comment by vpeil** [comment]
@phochste sure. Just as a comment? Or would like this info somewhere else?

**Comment by phochste** [comment]
@vpeil  See https://github.com/LibreCat/LibreCat/wiki/Upgrade-Nora-to-Oscar 

Search for TODO

**Comment by vpeil** [comment]
done

**Pull request merged**
