### PR TITLE
Update features.yml

### PR DESCRIPTION
**Pull request by christianmahnke**
Also use facets in the frontend. This change makes the off the shelf LibreCat a bit more like https://pub.uni-bielefeld.de/publication

### CODE REVIEW

**Comment by vpeil** [comment]
I think it is easier to put it in your layer, rather than having others removing it from their layers....
But, to do others think?

**Comment by christianmahnke** [comment]
Well, it is actually a feature that you might want to showcase on demo.librecat.org.

**Comment by vpeil** [comment]
yeah, I see the case for the demo server

**Comment by vpeil** [comment]
I'll put it into a layer for the demo server

**Pull request closed without merging**
